### ISSUE TITLE
Homepage press module 

### ISSUE THREAD

**Issue by RachaelYaeger** [human-nyc/inez#106]
Design here: https://cl.ly/1J1P001c1L0z
+ here http://clients.quitefranklyn.com/inez/060917/

@rinaldylaguerre did you finish this one? Can you guys give me directions on editing this to appear on staging?

**Comment by RachaelYaeger** [comment]
@rinaldylaguerre so sorry ahhh:
- [ ] Logos and type should be white 
- [ ] Homepage pagination arrows here: https://cl.ly/383N0C3c093N
- [ ] check font size 
- [ ] looks like we should be able to see the next and previous left and right logos slightly greyed https://cl.ly/0T3U3J0H2e0g

**Comment by rinaldylaguerre** [comment]
@RachaelYaeger I can't make the logos white since it's an image they're uploading. They have to download the white version of the logo from the companies' respective media assets kit or do their proper googles

**Comment by rinaldylaguerre** [comment]
@RachaelYaeger The pagination arrows already exist, but the font we're using does not support the white circle unicode if they wanted that specific one.

**Comment by RachaelYaeger** [comment]
Hey @rinaldylaguerre okay cool! Lemme know when you push to staging :) and I'll look!

**Comment by RachaelYaeger** [comment]
Do you know the recommended logo size?

**Comment by rinaldylaguerre** [comment]
@RachaelYaeger minimum height of 100px, width will scale

**Comment by RachaelYaeger** [comment]
@rinaldylaguerre looks like the dots could be a lilllllll smaller https://cl.ly/0T3U3J0H2e0g
