### ISSUE TITLE
[Footer] email capture: When an email has been entered can the same field that said "enter your email" can be programmed to say "You're on the list"

### ISSUE THREAD

**Issue by RachaelYaeger** [human-nyc/inez#108]
- [x]  @rinaldylaguerre can hitting the enter key to also input the email address? TY!

**Comment by rinaldylaguerre** [comment]
@RachaelYaeger enter key already does that

**Comment by RachaelYaeger** [comment]
Hey @rinaldylaguerre gettinnngggg sooo closseee!!! I hit enter and it takes me automatically to a new tab where MailChimp opens -- can the form turn into "You're on the list" in the same styling that ENTER EMAIL is currently in?

**Comment by rinaldylaguerre** [comment]
@RachaelYaeger I would need access to their mail chimp, account to get the code under the hood to, stop the redirect on submit, so i can code in the changes they want

**Comment by RachaelYaeger** [comment]
@rinaldylaguerre MailChimp creds: 

Login: InezNYC
Pword: InezShoez2017!
