### ISSUE TITLE
Integrate: Tidio Chat into the Let's Chat button on the footer

### ISSUE THREAD

**Issue by RachaelYaeger** [human-nyc/inez#61]
"
Hello,

This is Martin from Tidio Chat support.

I'm just following up on your request to have the chat widget opened using a particular element on your website.

First of all, you will need to make sure the chat is installed manually via the JS code (available in Channels > Live Chat > Integration), as the API commands don't work with plugins. Once it's there, paste in another script before your chat's javascript installation code:

<script>
 function chatShow(e) { 
 tidioChatApi.method('popUpOpen'); 
 }
</script>
 
Once this is installed, you will need to make your button or text (link) start the action.

For that we will use a simple href: 

<a href="#" onclick="chatShow()" data-event="Clicked chat from contact page">YOUR TEXT</a>

This one is for a simple text, or...

<a href="#" onclick="chatShow()">
<img src="YOUR PHOTO URL ADDRESS"/>
</a>
 
...for an image, button.

The second part needs to be put into your contact, product or your main page with the HTML editor.

And that is it! Now after clicking on the link with the first method, or an image/button with the second, your chat widget will open up for your visitor."

**Comment by RachaelYaeger** [comment]
@rinaldylaguerre does this work now from the footer!? omg! :)

**Comment by rinaldylaguerre** [comment]
@RachaelYaeger it should, i followed their directions. But Whit is the one who can turn Tidio on or off. It's all linked appropriately

**Comment by RachaelYaeger** [comment]
@InezNY Can you double check this? Thank you!
